name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Compile files
        run: |
          npm run compile
      - name: Deploy files
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN_EXCLUDE: '["LICENSE", "index.html", "assets", "images", "favicon.ico"]'
          COMMIT_MESSAGE:  ${{ github.event.head_commit.message }} @ ${{ github.sha }} 🚀
