name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v1"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"

      - name: "Create GitHub release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            sweclockers-dark.min.css
            sweclockers-dark.user.styl
